# Generated by Django 4.2.16 on 2024-11-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("rating_number", models.IntegerField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
                ("description", models.JSONField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("images", models.JSONField(blank=True, null=True)),
                ("videos", models.JSONField(blank=True, null=True)),
                ("store", models.CharField(max_length=100)),
                ("categories", models.JSONField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, null=True)),
                ("parent_asin", models.CharField(blank=True, max_length=10, null=True)),
                ("bought_together", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
