# Generated by Django 4.2.16 on 2024-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_sanpham_rating_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("images", models.TextField()),
                ("asin", models.CharField(max_length=50)),
                ("parent_asin", models.CharField(blank=True, max_length=50, null=True)),
                ("user_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("helpful_vote", models.IntegerField()),
                ("verified_purchase", models.BooleanField()),
                ("processed_text", models.TextField()),
                ("sentiment", models.CharField(max_length=20)),
                ("sentiment_text", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("predicted_sentiment", models.CharField(max_length=20)),
                ("predicted_sentiment_text", models.TextField()),
            ],
        ),
    ]
