# Generated by Django 5.1.3 on 2024-11-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
