# Generated by Django 5.1.3 on 2024-11-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_productreview_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="predicted_sentiment_text",
        ),
        migrations.RemoveField(
            model_name="productreview",
            name="sentiment_text",
        ),
    ]
